# Generated by Django 5.0.6 on 2024-05-12 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('developer_photo', models.ImageField(blank=True, null=True, upload_to='dev_photo/')),
                ('ref_to_social', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('game_photo', models.ImageField(blank=True, null=True, upload_to='games_photo/')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.gamedeveloper')),
            ],
        ),
    ]
