# Generated by Django 4.2.13 on 2024-05-31 07:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100),
        ),
    ]
